name: graduation
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^3.0.2+2
  like_button: ^2.0.2
  provider: ^5.0.0  
  image_picker: ^0.7.5+2
  # image_picker_for_web: ^2.0.0
  flutter_web_image_picker: ^0.0.2 
  intl: ^0.17.0
  http: ^0.13.3   
  material_floating_search_bar: ^0.3.3
  autocomplete_textfield: ^1.7.3
  google_fonts: ^2.0.0
  responsive_builder: ^0.4.1
  get: ^4.1.3
  font_awesome_flutter: ^9.0.0
  dropdownfield: ^1.0.3
  shimmer: ^2.0.0
  dio: ^4.0.0
  # localstorage: ^3.0.1+4
  shared_preferences: ^2.0.5
  flutter_form_bloc: ^0.20.1
  im_stepper: ^0.1.3
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  steps: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/pics/CONNECTION.jfif
    - lib/assets/pics/RashedGhunaim.jpg
    - lib/assets/pics/CommunicationG.png
    - lib/assets/pics/shae_manager2.png
    - lib/assets/pics/ells_logo_4_2.png
    - lib/assets/pics/ells_logo_4_1.png
    - lib/assets/pics/People family.png
    - lib/assets/pics/illustrator - Copy.png
    - lib/assets/pics/gg.jfif
    - lib/assets/pics/Loading Gif.gif
    - lib/assets/pics/like.jfif
    - lib/assets/pics/love.jfif
    - lib/assets/pics/clap.jfif
    - lib/assets/pics/comment.jfif
    - lib/assets/pics/share.png
    - lib/assets/pics/send.jfif
    - lib/assets/pics/profile.jfif
    - lib/assets/pics/add.jfif
    - lib/assets/pics/camera.jfif
    - lib/assets/pics/video.png
    - lib/assets/pics/document.jfif
    - lib/assets/pics/Bill Gates.jfif
    - lib/assets/pics/climate change.jfif
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PostDetails
      fonts:
        - asset: lib/assets/icons/PostDetails.ttf
    - family: DropDown3
      fonts:
        - asset: lib/assets/icons/DropDown3.ttf
    - family: DropDown2
      fonts:
        - asset: lib/assets/icons/DropDown2.ttf
    - family: DropDown1
      fonts:
        - asset: lib/assets/icons/DropDown1.ttf
    - family: RAR
      fonts:
        - asset: lib/assets/icons/RAR.ttf
    - family: HandsShake2
      fonts:
        - asset: lib/assets/icons/HandsShake2.ttf
    - family: HandsShake
      fonts:
        - asset: lib/assets/icons/HandsShake.ttf
    - family: Presentation
      fonts:
        - asset: lib/assets/icons/Presentation.ttf
    - family: Manage
      fonts:
        - asset: lib/assets/icons/Manage.ttf
    - family: FeedBack
      fonts:
        - asset: lib/assets/icons/FeedBack.ttf
    - family: Questionaries2
      fonts:
        - asset: lib/assets/icons/Questionaries2.ttf
    - family: Questionaries
      fonts:
        - asset: lib/assets/icons/Questionaries.ttf
    - family: Snooze
      fonts:
        - asset: lib/assets/icons/Snooze.ttf
    - family: AddImage2
      fonts:
        - asset: lib/assets/icons/AddImage2.ttf
    - family: AddImage
      fonts:
        - asset: lib/assets/icons/AddImage.ttf
    - family: AddLink
      fonts:
        - asset: lib/assets/icons/AddLink.ttf
    - family: GoogleDoc
      fonts:
        - asset: lib/assets/icons/GoogleDoc.ttf
    - family: Drive
      fonts:
        - asset: lib/assets/icons/Drive.ttf
    - family: Cancel
      fonts:
        - asset: lib/assets/icons/Cancel.ttf
    - family: Delete
      fonts:
        - asset: lib/assets/icons/Delete.ttf
    - family: ThreeTopDots
      fonts:
        - asset: lib/assets/icons/ThreeTopDots.ttf
    - family: Related
      fonts:
        - asset: lib/assets/icons/Related.ttf
    - family: Experts
      fonts:
        - asset: lib/assets/icons/Experts.ttf
    - family: Edit2
      fonts:
        - asset: lib/assets/icons/Edit2.ttf
    - family: Image
      fonts:
        - asset: lib/assets/icons/Image.ttf
    - family: Add
      fonts:
        - asset: lib/assets/icons/Add.ttf
    - family: Group
      fonts:
        - asset: lib/assets/icons/Group.ttf
    - family: Unfollow
      fonts:
        - asset: lib/assets/icons/Unfollow.ttf
    - family: Report
      fonts:
         - asset: lib/assets/icons/Report.ttf
    - family: BookMark
      fonts:
         - asset: lib/assets/icons/BookMark.ttf
    - family: UpArrow
      fonts:
         - asset: lib/assets/icons/UpArrow.ttf
    - family: More
      fonts:
         - asset: lib/assets/icons/More.ttf
    - family: Edit
      fonts:
         - asset: lib/assets/icons/Edit.ttf
    - family: Request
      fonts:
         - asset: lib/assets/icons/Request.ttf
    - family: UserDashboard
      fonts:
         - asset: lib/assets/icons/UserDashboard.ttf
    - family: Network
      fonts:
          - asset: lib/assets/icons/Network.ttf
    - family: Home
      fonts:
          - asset: lib/assets/icons/Home.ttf
    - family: Laghing
      fonts:
          - asset: lib/assets/icons/Laghing.ttf
    - family: Love
      fonts:
          - asset: lib/assets/icons/Love.ttf
    - family: Share
      fonts:
          - asset: lib/assets/icons/Share.ttf
    - family: Comment
      fonts:
        - asset: lib/assets/icons/Comment.ttf
    - family: Like
      fonts:
        - asset: lib/assets/icons/Like.ttf
    - family: Sent
      fonts:
        - asset: lib/assets/icons/Sent.ttf
    - family: ChartPie
      fonts:
        - asset: lib/assets/icons/ChartPie.ttf
    - family: Account
      fonts:
        - asset: lib/assets/icons/Account.ttf
    - family: Chatting
      fonts:
        - asset: lib/assets/icons/Chatting.ttf
    - family: Lobster-Regular
      fonts:
        - asset: lib/assets/fonts/Lobster-Regular.ttf
    - family: Tangerine-Regular
      fonts:
        - asset: lib/assets/fonts/Tangerine-Regular.ttf
    - family: Google
      fonts:
        - asset: lib/assets/icons/Google.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
